# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'egg_lane_proc_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(281, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drawLanesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.drawLanesGroupBox.setGeometry(QtCore.QRect(10, 0, 261, 281))
        self.drawLanesGroupBox.setObjectName("drawLanesGroupBox")
        self.drawLanesButton = QtWidgets.QPushButton(self.drawLanesGroupBox)
        self.drawLanesButton.setGeometry(QtCore.QRect(60, 170, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.drawLanesButton.setFont(font)
        self.drawLanesButton.setObjectName("drawLanesButton")
        self.layoutWidget_3 = QtWidgets.QWidget(self.drawLanesGroupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 60, 241, 50))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectedExperimentStaticLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedExperimentStaticLabel.setFont(font)
        self.selectedExperimentStaticLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedExperimentStaticLabel.setObjectName("selectedExperimentStaticLabel")
        self.verticalLayout.addWidget(self.selectedExperimentStaticLabel)
        self.selectedExperimentLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectedExperimentLabel.setFont(font)
        self.selectedExperimentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedExperimentLabel.setObjectName("selectedExperimentLabel")
        self.verticalLayout.addWidget(self.selectedExperimentLabel)
        self.selectExperimentButton = QtWidgets.QPushButton(self.drawLanesGroupBox)
        self.selectExperimentButton.setGeometry(QtCore.QRect(60, 20, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectExperimentButton.setFont(font)
        self.selectExperimentButton.setObjectName("selectExperimentButton")
        self.assignLanesButton = QtWidgets.QPushButton(self.drawLanesGroupBox)
        self.assignLanesButton.setGeometry(QtCore.QRect(50, 240, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assignLanesButton.setFont(font)
        self.assignLanesButton.setObjectName("assignLanesButton")
        self.overwriteLanesCheckBox = QtWidgets.QCheckBox(self.drawLanesGroupBox)
        self.overwriteLanesCheckBox.setGeometry(QtCore.QRect(10, 210, 241, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.overwriteLanesCheckBox.setFont(font)
        self.overwriteLanesCheckBox.setObjectName("overwriteLanesCheckBox")
        self.firstVidSecToSkipLabel = QtWidgets.QLabel(self.drawLanesGroupBox)
        self.firstVidSecToSkipLabel.setGeometry(QtCore.QRect(40, 120, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstVidSecToSkipLabel.setFont(font)
        self.firstVidSecToSkipLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.firstVidSecToSkipLabel.setObjectName("firstVidSecToSkipLabel")
        self.firstVidSecToSkipLineEdit = QtWidgets.QLineEdit(self.drawLanesGroupBox)
        self.firstVidSecToSkipLineEdit.setGeometry(QtCore.QRect(70, 140, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.firstVidSecToSkipLineEdit.setFont(font)
        self.firstVidSecToSkipLineEdit.setText("")
        self.firstVidSecToSkipLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.firstVidSecToSkipLineEdit.setPlaceholderText("")
        self.firstVidSecToSkipLineEdit.setObjectName("firstVidSecToSkipLineEdit")
        self.removeLanesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.removeLanesGroupBox.setGeometry(QtCore.QRect(10, 290, 261, 251))
        self.removeLanesGroupBox.setObjectName("removeLanesGroupBox")
        self.numOriginalContoursValueLabel = QtWidgets.QLabel(self.removeLanesGroupBox)
        self.numOriginalContoursValueLabel.setGeometry(QtCore.QRect(50, 80, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numOriginalContoursValueLabel.setFont(font)
        self.numOriginalContoursValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numOriginalContoursValueLabel.setObjectName("numOriginalContoursValueLabel")
        self.removeLanesButton = QtWidgets.QPushButton(self.removeLanesGroupBox)
        self.removeLanesButton.setGeometry(QtCore.QRect(60, 160, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeLanesButton.setFont(font)
        self.removeLanesButton.setObjectName("removeLanesButton")
        self.lanesToRemoveLabel = QtWidgets.QLabel(self.removeLanesGroupBox)
        self.lanesToRemoveLabel.setGeometry(QtCore.QRect(70, 110, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lanesToRemoveLabel.setFont(font)
        self.lanesToRemoveLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lanesToRemoveLabel.setObjectName("lanesToRemoveLabel")
        self.numOriginalContoursTextLabel = QtWidgets.QLabel(self.removeLanesGroupBox)
        self.numOriginalContoursTextLabel.setGeometry(QtCore.QRect(40, 60, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numOriginalContoursTextLabel.setFont(font)
        self.numOriginalContoursTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numOriginalContoursTextLabel.setObjectName("numOriginalContoursTextLabel")
        self.numContoursAfterLaneRemoveTextLabel = QtWidgets.QLabel(self.removeLanesGroupBox)
        self.numContoursAfterLaneRemoveTextLabel.setGeometry(QtCore.QRect(20, 200, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numContoursAfterLaneRemoveTextLabel.setFont(font)
        self.numContoursAfterLaneRemoveTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numContoursAfterLaneRemoveTextLabel.setObjectName("numContoursAfterLaneRemoveTextLabel")
        self.numContoursAfterLaneRemoveValueLabel = QtWidgets.QLabel(self.removeLanesGroupBox)
        self.numContoursAfterLaneRemoveValueLabel.setGeometry(QtCore.QRect(30, 220, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numContoursAfterLaneRemoveValueLabel.setFont(font)
        self.numContoursAfterLaneRemoveValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numContoursAfterLaneRemoveValueLabel.setObjectName("numContoursAfterLaneRemoveValueLabel")
        self.lanesToRemoveLineEdit = QtWidgets.QLineEdit(self.removeLanesGroupBox)
        self.lanesToRemoveLineEdit.setGeometry(QtCore.QRect(10, 130, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lanesToRemoveLineEdit.setFont(font)
        self.lanesToRemoveLineEdit.setText("")
        self.lanesToRemoveLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lanesToRemoveLineEdit.setObjectName("lanesToRemoveLineEdit")
        self.loadContoursFileButton = QtWidgets.QPushButton(self.removeLanesGroupBox)
        self.loadContoursFileButton.setGeometry(QtCore.QRect(60, 20, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadContoursFileButton.setFont(font)
        self.loadContoursFileButton.setObjectName("loadContoursFileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.drawLanesGroupBox.setTitle(_translate("MainWindow", "Draw Lanes"))
        self.drawLanesButton.setText(_translate("MainWindow", "Draw Lanes"))
        self.selectedExperimentStaticLabel.setText(_translate("MainWindow", "Selected Experiment"))
        self.selectedExperimentLabel.setText(_translate("MainWindow", "<ExperimentName>"))
        self.selectExperimentButton.setText(_translate("MainWindow", "Select Experiment"))
        self.assignLanesButton.setText(_translate("MainWindow", "Assign Lanes and Times"))
        self.overwriteLanesCheckBox.setText(_translate("MainWindow", "Overwrite Previous Lane Assignment?"))
        self.firstVidSecToSkipLabel.setText(_translate("MainWindow", "First Video Seconds to Skip"))
        self.removeLanesGroupBox.setTitle(_translate("MainWindow", "Remove Lanes"))
        self.numOriginalContoursValueLabel.setText(_translate("MainWindow", "<NumOriginalContours>"))
        self.removeLanesButton.setText(_translate("MainWindow", "Remove Lanes"))
        self.lanesToRemoveLabel.setText(_translate("MainWindow", "Lanes to Remove"))
        self.numOriginalContoursTextLabel.setText(_translate("MainWindow", "Num Original Contours"))
        self.numContoursAfterLaneRemoveTextLabel.setText(_translate("MainWindow", "Num Contours After Lane Removal"))
        self.numContoursAfterLaneRemoveValueLabel.setText(_translate("MainWindow", "<NumContoursAfterLaneRemove>"))
        self.loadContoursFileButton.setText(_translate("MainWindow", "Load Contours File"))

