# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'egg_vid_anno_main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.threeEggsLabel = QtWidgets.QLabel(self.centralwidget)
        self.threeEggsLabel.setGeometry(QtCore.QRect(80, 290, 70, 20))
        self.threeEggsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.threeEggsLabel.setObjectName("threeEggsLabel")
        self.adultLabel = QtWidgets.QLabel(self.centralwidget)
        self.adultLabel.setGeometry(QtCore.QRect(150, 290, 70, 20))
        self.adultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.adultLabel.setObjectName("adultLabel")
        self.twoEggsLabel = QtWidgets.QLabel(self.centralwidget)
        self.twoEggsLabel.setGeometry(QtCore.QRect(10, 290, 70, 20))
        self.twoEggsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.twoEggsLabel.setObjectName("twoEggsLabel")
        self.eggLabel = QtWidgets.QLabel(self.centralwidget)
        self.eggLabel.setGeometry(QtCore.QRect(290, 290, 70, 20))
        self.eggLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.eggLabel.setObjectName("eggLabel")
        self.l1Label = QtWidgets.QLabel(self.centralwidget)
        self.l1Label.setGeometry(QtCore.QRect(360, 290, 70, 20))
        self.l1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.l1Label.setObjectName("l1Label")
        self.junkLabel = QtWidgets.QLabel(self.centralwidget)
        self.junkLabel.setGeometry(QtCore.QRect(220, 290, 70, 20))
        self.junkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.junkLabel.setObjectName("junkLabel")
        self.selectContoursFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectContoursFileButton.setGeometry(QtCore.QRect(149, 10, 140, 30))
        self.selectContoursFileButton.setObjectName("selectContoursFileButton")
        self.startAnnoButton = QtWidgets.QPushButton(self.centralwidget)
        self.startAnnoButton.setGeometry(QtCore.QRect(149, 250, 140, 30))
        self.startAnnoButton.setObjectName("startAnnoButton")
        self.createAnnoFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.createAnnoFileButton.setGeometry(QtCore.QRect(150, 50, 140, 30))
        self.createAnnoFileButton.setObjectName("createAnnoFileButton")
        self.getLastAnnoButton = QtWidgets.QPushButton(self.centralwidget)
        self.getLastAnnoButton.setGeometry(QtCore.QRect(150, 90, 140, 30))
        self.getLastAnnoButton.setObjectName("getLastAnnoButton")
        self.vidNumLabel = QtWidgets.QLabel(self.centralwidget)
        self.vidNumLabel.setGeometry(QtCore.QRect(90, 130, 120, 30))
        self.vidNumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.vidNumLabel.setObjectName("vidNumLabel")
        self.vidNumLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.vidNumLineEdit.setGeometry(QtCore.QRect(210, 130, 80, 30))
        self.vidNumLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.vidNumLineEdit.setObjectName("vidNumLineEdit")
        self.cntFileIndexLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cntFileIndexLineEdit.setGeometry(QtCore.QRect(210, 170, 80, 30))
        self.cntFileIndexLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cntFileIndexLineEdit.setObjectName("cntFileIndexLineEdit")
        self.cntFileIndexLabel = QtWidgets.QLabel(self.centralwidget)
        self.cntFileIndexLabel.setGeometry(QtCore.QRect(90, 170, 120, 30))
        self.cntFileIndexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cntFileIndexLabel.setObjectName("cntFileIndexLabel")
        self.annoFileCreatedLabel = QtWidgets.QLabel(self.centralwidget)
        self.annoFileCreatedLabel.setGeometry(QtCore.QRect(300, 50, 50, 30))
        self.annoFileCreatedLabel.setText("")
        self.annoFileCreatedLabel.setObjectName("annoFileCreatedLabel")
        self.annoFileIndexLabel = QtWidgets.QLabel(self.centralwidget)
        self.annoFileIndexLabel.setGeometry(QtCore.QRect(90, 210, 120, 30))
        self.annoFileIndexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.annoFileIndexLabel.setObjectName("annoFileIndexLabel")
        self.annoFileIndexLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.annoFileIndexLineEdit.setGeometry(QtCore.QRect(210, 210, 80, 30))
        self.annoFileIndexLineEdit.setText("")
        self.annoFileIndexLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.annoFileIndexLineEdit.setObjectName("annoFileIndexLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.threeEggsLabel.setText(_translate("MainWindow", "2 Eggs (w)"))
        self.adultLabel.setText(_translate("MainWindow", "Adult (e)"))
        self.twoEggsLabel.setText(_translate("MainWindow", "Cluster (q)"))
        self.eggLabel.setText(_translate("MainWindow", "Egg (t)"))
        self.l1Label.setText(_translate("MainWindow", "L1 (y)"))
        self.junkLabel.setText(_translate("MainWindow", "Junk (r)"))
        self.selectContoursFileButton.setText(_translate("MainWindow", "Select Contours File"))
        self.startAnnoButton.setText(_translate("MainWindow", "Start Annotating"))
        self.createAnnoFileButton.setText(_translate("MainWindow", "Create Annotations File"))
        self.getLastAnnoButton.setText(_translate("MainWindow", "Get Last Annotation"))
        self.vidNumLabel.setText(_translate("MainWindow", "Video Number"))
        self.cntFileIndexLabel.setText(_translate("MainWindow", "Contours File Index"))
        self.annoFileIndexLabel.setText(_translate("MainWindow", "Annotations File Index"))

